= (W I P) Quarkus vlille demo



== Description

Use the public API of the MEL (Metropole Européenne Lilloise) and display the available bike numbers around my home.
The main *objective* is to discover new tools and ways of programming.

* Native compilation.
* Reactive Programming.
* Containerize the application.
* Use a NoSql database.
* Remote programming with Github CodeSpace and IntelliJ gateway

#Quarkus #CodeSpace #MongoDb #Panache #Mutiny #Docker

== Features

Spec:

* Retrieve from MEL API the Ville terminals information
* Store them in BSON in mongodb
* Provide an endpoint to display this data.
** Stations are grouped by name, and only the most recent line is present.
** During the first call, in non-blocking execution way, we cache the stations and we emulate a long operation  with a thread sleep

=== Build

[source,bash]
----
./tool.sh build-image
----

=== Start


[source,bash]
----
./tool.sh env-dev up
mv compile quarkus:dev

or

./tool.sh env-run up
----

=== Test

[source,bash]
----
./tool.sh env-test-run up
----