version: '3.7'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./docker-entrypoint-initdb.d/z.liquibase.js:/docker-entrypoint-initdb.d/z.liquibase.js

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
 
#    docker run --rm -d -p 4444:4444 -p 6900:5900 -p 9515:9515 --add-host host.docker.internal:host-gateway --name selenium -v /dev/shm:/dev/shm selenium/standalone-chrome:3.141.59-bismuth
  selenium:
    image: selenium/standalone-chrome:3.141.59-bismuth
    ports:
      - 4444:4444
      - 6900:5900
      - 9515:9515
    volumes:
      - /dev/shm:/dev/shm

  quarkus:
    image: codespace/getting-started:1.0-SNAPSHOT
    ports:
      - 8080:8080


