version: '3.7'

services:
  quarkus:
    build: 
      context: /workspaces/main/quarkus-vlille-demo
      dockerfile: /workspaces/main/quarkus-vlille-demo/src/main/docker/Dockerfile.vlille.jvm
      target: run-dev-stack
    image: codespace/quarkus-vlille-demo:1.0-SNAPSHOT
    ports:
      - 8080:8080