name: build
on: 
  workflow_dispatch:

jobs:
  run-npm-install:
    runs-on: ubuntu-latest
    steps:
        - name: checkout
          uses: actions/checkout@v2

        - name: Cache maven repository
          id: cache-mvn
          uses: actions/cache@v3
          env:
            cache-name: cache-mvn-repo
          with:
            # mvn cache files are stored in `~/.m2` on Linux/macOS
            path: |
              ./m2
            key: ${{ runner.os }}-build-${{ env.cache-name }}-1${{ hashFiles('**/pom.xml') }}
            restore-keys: |
              ${{ runner.os }}-build-${{ env.cache-name }}-
              ${{ runner.os }}-build-
              ${{ runner.os }}-

        - if: ${{ steps.cache-npm.outputs.cache-hit == false }}
          name: List the state of maven dependencies
          continue-on-error: true
          run: mvn dependency:list



        - name : setup node
          uses: actions/setup-java@v3
          with:
            distribution: 'temurin'
            java-version: '17'
            cache: 'maven'
    cache: 'maven'
        - name: run install
          shell: bash
          run: |
            npm install

  run-npm-test:
    needs: run-npm-install
    runs-on: ubuntu-latest
    steps:
        - name: checkout
          uses: actions/checkout@v2
        - name: Cache node modules
          id: cache-npm
          uses: actions/cache@v3
          env:
            cache-name: cache-node-modules
          with:
            # npm cache files are stored in `~/.npm` on Linux/macOS
            path: |
              ./node_modules
            key: ${{ runner.os }}-build-${{ env.cache-name }}-1${{ hashFiles('**/package-lock.json') }}
            restore-keys: |
              ${{ runner.os }}-build-${{ env.cache-name }}-
              ${{ runner.os }}-build-
              ${{ runner.os }}-

        - if: ${{ steps.cache-npm.outputs.cache-hit == false }}
          name: Install if cache-hit false
          continue-on-error: true
          run: npm install
        - name : setup node
          uses: actions/setup-node@v2
          with:
            node-version: 'lts/*'
        - name: run test
          shell: bash
          run: |
            npm test